### ISSUE TITLE
关于配置环境

### ISSUE THREAD

**Issue by zjutkarma** [OpenLMLab/MOSS-RLHF#23]
我的trition版本是1.0.0，但是我在运行run_en.py时报错：
AttributeError: module 'triton.language' has no attribute 'constexpr'
网上的解决方案说需要把trition升级到2.0.0
但我尝试过，deepspeed又会出现和trition版本兼容的问题
运行不起来run_en.py

**Comment by CiaranZhou** [comment]
Hi~ 很高兴你能够follow我们的工作

首先想要确认的是环境的安装方式是否与[我们的Setup](https://github.com/OpenLMLab/MOSS-RLHF#-requirements--setup)一致

> 在运行run_en.py时报错：AttributeError: module 'triton.language' has no attribute 'constexpr'

关于这一点，能否展示更多的报错信息

> deepspeed又会出现和trition版本兼容的问题

针对这一点具体是指哪方面的问题呢？

在已经安装了2.0.0版本的triton的情况下以下DeepSpeed安装方式也许可以解决你的问题 : )
`DS_BUILD_OPS=1 DS_BUILD_SPARSE_ATTN=0 pip install deepspeed`

**Comment by zjutkarma** [comment]
谢谢你的解答～已解决～

**Comment by Eversee22** [comment]
请问怎么解决的
