### ISSUE TITLE
[Question] Adaptive Margin

### ISSUE THREAD

**Issue by eyuansu62** [OpenLMLab/MOSS-RLHF#40]
In the newly report, Adaptive Margin is introduced and it has a great performance. And it seems that Adaptive Margin function is calculated by the mean of N reward model. Does it cost too much?

**Comment by refrain-wbh** [comment]
The approach of "the mean of N reward model" involves precomputing soft labels for the dataset, with no difference in training cost compared to the baseline model during actual training. It merely involves modifying the labels of the data, possibly resulting in fewer and more stable labels, as it quickly reduces the loss to a lower level without fluctuation. On the other hand, "the mean of N reward model" is merely a simple implementation of Adaptive Margin, and high-quality soft labels obtained through other means can also have a similar effect.

**Comment by refrain-wbh** [comment]
Adaptive Margin involves precomputing margin for the dataset, with no difference in training cost compared to the baseline model during actual training.

**Comment by eyuansu62** [comment]
Is the model used in precomputing margin the same as baseline model?

**Comment by eyuansu62** [comment]
Is the model used in precomputing margin same as the baseline model?

**Comment by refrain-wbh** [comment]
Yes,  models used to pre-determine the margin are trained without any additional techniques but only through changing seed.
