### ISSUE TITLE
The release of reward model training code?

### ISSUE THREAD

**Issue by hejujie** [OpenLMLab/MOSS-RLHF#6]
It's an excellent paper and has a significant contribution to the entire alignment community. 
I wanted to inquire if you have any plans to open-source the training code for the reward model.

**Comment by Ablustrund** [comment]
Thank you for your great supports to us!
Because reward model training involves more methods, this part will be explained in the second part of the technical report, thank you for your support and recognition!

**Comment by hejujie** [comment]
Thank you for your response. May I know if there is a specific timeline for the release of the second part of the technical report?

**Comment by Ablustrund** [comment]
> 

Probably in August or September of this year, thanks for your interest.
